services:
  aiohttp-app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    command: bash -c "python create_table.py && python main.py"

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=aiohttp_hw
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
