### Create advert
POST http://127.0.0.1:8080/api/adverts
Content-Type: application/json

{
  "title": "Test Title",
  "description": "Test Description",
  "owner": "Test User"
}

### Update advert
PUT http://127.0.0.1:8080/api/advert/1
Content-Type: application/json

{
  "title": "Test Title",
  "description": "Update Description",
  "owner": "Test Users"
}

### Get all adverts
GET http://127.0.0.1:8080/api/adverts
Accept: application/json

### Get advert with id
GET http://127.0.0.1:8080/api/advert/2
Accept: application/json

### Delete advert
DELETE http://127.0.0.1:8080/api/advert/2
Accept: application/json
